# HW 1

## instructions

our course will be using an automatic grading system. <br>
after each question there will appear a code block with some prepared code to add your answer to a dictionary that will be sent to the course server for grading. <br>
please do not edit any code other than in placeholders marked `#### your code here ####` <br>
don't forget to run the code block after you write your answer.


you can add code blocks wherever you want in order to interact with datasets and play with your own code. <br>
in the next code block plase fill in your id number and email account in the appropriate placees. <br>
and don't forget to run the block!

In [1]:
ans = {}
ans['HW'] = 'HW1'
ans['id_number'] = 307923383
ans['email'] = "somer@mail.tau.ac.il"

for multiple choice questions, replace the placeholder `#### your answer here ####` with the apropreate number.<br>
let's practice with this example question:

#### do you understand the instructions?
1. no
2. yes
3. not at all

In [2]:
ans['example'] = 2

# math refresher

## Algebra

#### Q1. Given column vector $x$ of length $n$, what kind of object is $x x^t$  and what is its rank?

1. $n\times n$ matrix, rank can be between $1$ and $n$

2. $n \times 1$ matrix (a vector), rank is $1$

3. $n\times  n$ matrix, rank is $1$

4. $1 \times 1$ matrix (a scalar), rank is $1$


In [3]:
ans['Q1'] = 3

#### Q2. Given a matrix $X_{n\times n}$, what conditions are required for it to be invertible

1. That it is full rank, and the main diagonal elements are not 0

2. That all its main diagonal elements are not 0

3. That it is full rank

4. That its main diagonal is all ones


In [4]:
ans['Q2'] = 3

## probability

#### Q3. $X , Y$ are random variables, which of the following is true: 

1. $E(X+Y) = E(X) + E(Y)$ and $E(XY) = E(X)E(Y)$

2. $Var(X+Y) = Var(X) + Var(Y)$ if $X, Y$ are independent

3. $Var(X+Y) = Var(X) + Var(X) + Cov(X,Y)$

4. Both 1 and 3

In [5]:
ans['Q3'] = 2

#### Q4. We have a fair coin, and we define a random variable that is equal 1 if heads come up and 0 if tails. What kind of distribution do the outcome of a single flip and the sum of outcomes of 10 flips have?

1. $Uniform(0,1)$ and $Bernoulli(1)$, respectively

2. $Poisson(1)$ and $Poisson(10)$, respectively

3. $Bernoulli(1)$ and $Bernoulli(10)$, respectively

4. $Bernoulli(0.5)$ and $Binomial(10,0.5)$, respectively

In [6]:
ans['Q4'] = 4

#### Q5. I am throwing a fair dice twice, what is the conditional probability that the first throw gives 1, GIVEN that the sum of the throws is 3? 

1. $^1/_2$

2. $1$

3. $^1/_6$

4. $^1/_3$


In [7]:
ans['Q5'] = 1

#### Q6. In the same situation, what is the probability that the sum is 3 AND the first throw gives 1?

1. $^1/_6$

2. $^1/_{36}$

3. $^1/_{18}$

4. $^1/_4$ 


In [8]:
ans['Q6'] = 2

# python

## Basics

#### Q7. Which one of the following List Comprehensions would create a list containing all prime numbers under 100?

1. `[possiblePrime for possiblePrime in range(2, 100) for num in range(2, possiblePrime) if possiblePrime % num != 0] `

2. `[possiblePrime for possiblePrime in range(2, 100) if all(possiblePrime % num != 0 for num in range(2, possiblePrime))]`

3. `list({possiblePrime for possiblePrime in range(2, 100) for num in range(2, possiblePrime) if possiblePrime % num == 0})`

4. `{i: possiblePrime for i, possiblePrime in enumerate(range(2, 100)) if all(possiblePrime % num != 0 for num in range(2, possiblePrime))}`


In [14]:
ans['Q7'] = 2

## Numpy

#### Q8. What does the following statement do, from left to right? (assume `import numpy as np`)

```
(np.zeros((3, 3)) + 1) / np.array([1, 2, 3])
```

1. It creates a 3x3 array of zeros, adds 1 to all values and divides each row elementwise by the row [1, 2, 3]

2. It creates a 3x3 array of zeros, then throws an exception for trying to add a constant to a numpy array

3. It takes a tuple (3,3), makes it (0,0), adds 1 to all values and divides each row elementwise by the row [1, 2, 3]

4. It creates a 3x3 array of zeros, adds 1 to all values, then throws an exception for trying to divide a 3x3 array with a 1D arrray


In [16]:
import numpy as np

In [17]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
(np.zeros((3,3)) + 1)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
(np.zeros((3,3)) + 1) / np.array([1,2,3])

array([[1.        , 0.5       , 0.33333333],
       [1.        , 0.5       , 0.33333333],
       [1.        , 0.5       , 0.33333333]])

In [20]:
ans['Q8'] = 1

#### Q9. What will be the output of the following statement? (Make sure you understand why)

```
np.array(range(10))[1:-2][::-3].sum()
```

1. 12

2. 15

3. 20

4. 28


In [21]:
np.array(range(10))[1:-2][::-3].sum()

12

In [23]:
np.array(range(10))[1:-2]

array([1, 2, 3, 4, 5, 6, 7])

In [24]:
np.array(range(10))[1:-2][::-3]

array([7, 4, 1])

In [22]:
ans['Q9'] = 1

## Pandas

in this section we will be interacting with a real dataset.<br>
this next block loads the dataset from the repository. <br>
remember that you are able to add code blocks to interact with the dataset. <br>
if at any point you think that you might have altered the original data, you can simply rerun this code block to load a fresh copy.<br>
please do not change the blocks that record your answer to the "ans" dictionary. <br><br>

the pandas documentation, and specifically the list of DataFrame methods can be helpful: 
https://pandas.pydata.org/pandas-docs/stable/reference/frame.html

In [25]:
import pandas as pd
df_avocado = pd.read_csv('avocado_fixed.csv')
df_avocado.head()

Date  price  year  region
0  12/27/15   1.33  2015  Albany
1  12/20/15   1.35  2015  Albany
2  12/13/15   0.93  2015  Albany
3   12/6/15   1.08  2015  Albany
4  11/29/15   1.28  2015  Albany

#### Q10. on what date and region was the price the highest?

1. PhoenixTucson - 2/5/17

2. SanFrancisco - 10/30/16

3. Chicago - 10/8/17

4. LosAngeles 2/5/17

__Hint:__ the pandas data frame method `sort_values` can come in handy, look it up on the pandas documentation.

In [27]:
df_avocado.sort_values(by='price').tail()

Date  price  year        region
6053   10/1/17   2.14  2017       Chicago
6055   9/17/17   2.15  2017       Chicago
6370   10/8/17   2.19  2017   GrandRapids
5000  10/30/16   2.20  2016  SanFrancisco
6052   10/8/17   2.22  2017       Chicago

In [30]:
df_avocado.describe()

price         year
count  9126.000000  9126.000000
mean      1.158040  2016.147929
std       0.263041     0.939968
min       0.460000  2015.000000
25%       0.980000  2015.000000
50%       1.130000  2016.000000
75%       1.320000  2017.000000
max       2.220000  2018.000000

In [28]:
ans['Q10'] = 3

__Hint:__ `groupby` and `agg (aggregate)` are needed for the next questions, make sure you understand how to use them. you can use the recitation materials as reference. 

#### Q11. which region had the lowest price for the entire period? (on average)

1. Albany

2. PhoenixTucson

3. Houston

4. HartfordSpringfield

In [40]:
mean_price_per_region = df_avocado.groupby(by='region').mean()
mean_price_per_region.head()

price         year
region                                    
Albany               1.348757  2016.147929
Atlanta              1.068817  2016.147929
BaltimoreWashington  1.344201  2016.147929
Boise                1.076036  2016.147929
Boston               1.304379  2016.147929

In [45]:
mean_price_per_region.idxmin()['price']

'PhoenixTucson'

In [46]:
ans['Q11'] = 2

#### Q12. in what year were avocado prices the lowest? (on average)

1. 2015

2. 2016

3. 2017

4. 2018

In [47]:
df_avocado.head()

Date  price  year  region
0  12/27/15   1.33  2015  Albany
1  12/20/15   1.35  2015  Albany
2  12/13/15   0.93  2015  Albany
3   12/6/15   1.08  2015  Albany
4  11/29/15   1.28  2015  Albany

In [50]:
mean_price_per_year = df_avocado.groupby('year').mean(); mean_price_per_year

price
year          
2015  1.077963
2016  1.105595
2017  1.294888
2018  1.127886

In [52]:
mean_price_per_year.idxmin()['price']

2015

In [53]:
ans['Q12'] = 1

#### Q13. in what year were the prices lowest in Indianapolis? (on average)

1. 2015

2. 2016

3. 2017

4. 2018

In [54]:
df_avocado.head()

Date  price  year  region
0  12/27/15   1.33  2015  Albany
1  12/20/15   1.35  2015  Albany
2  12/13/15   0.93  2015  Albany
3   12/6/15   1.08  2015  Albany
4  11/29/15   1.28  2015  Albany

In [72]:
indianapolis_df = df_avocado[df_avocado.region == 'Indianapolis']
indianapolis_df.head()

Date  price  year        region
988  12/27/15   1.04  2015  Indianapolis
989  12/20/15   1.10  2015  Indianapolis
990  12/13/15   1.03  2015  Indianapolis
991   12/6/15   0.92  2015  Indianapolis
992  11/29/15   1.08  2015  Indianapolis

In [76]:
indianapolis_df.groupby('year').mean().idxmin()['price']

2018

In [77]:
ans['Q13'] = 4

we will now load some additional data to play with.<br>
the new data set holds number of avocado bags sold in each region for the same period.

In [79]:
import pandas as pd
df_avocado_bags = pd.read_csv('avocado_2_fixed.csv')
df_avocado_bags.head()

Date  num_bags  year  region
0  12/27/15   8696.87  2015  Albany
1  12/20/15   9505.56  2015  Albany
2  12/13/15   8145.35  2015  Albany
3   12/6/15   5811.16  2015  Albany
4  11/29/15   6183.95  2015  Albany

__notice:__ to answer the following questions you will need to join the two datasets together properly and make calculations on columns from both dfs. <br>
remember the appropriate method for joining DF's in pandas we discussed in the recitation.<br>
assume that the 'avocado market' for a single date can be measured by price times number of bags.

#### Q14. which of the following regions has a larger avocado market? (over the entire period)

1. California

2. NewYork

3. Chicago

4. LosAngeles

In [83]:
joined_df = pd.merge(df_avocado, df_avocado_bags, on=['Date', 'region', 'year'])
joined_df.head()

Date  price  year  region  num_bags
0  12/27/15   1.33  2015  Albany   8696.87
1  12/20/15   1.35  2015  Albany   9505.56
2  12/13/15   0.93  2015  Albany   8145.35
3   12/6/15   1.08  2015  Albany   5811.16
4  11/29/15   1.28  2015  Albany   6183.95

In [88]:
joined_df['market'] = joined_df['price'] * joined_df['num_bags']

In [89]:
joined_df.head()

Date  price  year  region  num_bags      market
0  12/27/15   1.33  2015  Albany   8696.87  11566.8371
1  12/20/15   1.35  2015  Albany   9505.56  12832.5060
2  12/13/15   0.93  2015  Albany   8145.35   7575.1755
3   12/6/15   1.08  2015  Albany   5811.16   6276.0528
4  11/29/15   1.28  2015  Albany   6183.95   7915.4560

In [94]:
1.33*8696.87

11566.837100000002

In [105]:
joined_df.groupby('region').sum().loc[['California', 'NewYork', 'Chicago', 'LosAngeles'], 'market']

region
California    2.554244e+08
NewYork       9.107116e+07
Chicago       2.192339e+07
LosAngeles    1.503435e+08
Name: market, dtype: float64

In [106]:
ans['Q14'] = 1

#### Q15. what year were avocado sales the highest (by total market value)

1. 2015

2. 2016

3. 2017

4. 2018

In [107]:
joined_df.head()

Date  price  year  region  num_bags      market
0  12/27/15   1.33  2015  Albany   8696.87  11566.8371
1  12/20/15   1.35  2015  Albany   9505.56  12832.5060
2  12/13/15   0.93  2015  Albany   8145.35   7575.1755
3   12/6/15   1.08  2015  Albany   5811.16   6276.0528
4  11/29/15   1.28  2015  Albany   6183.95   7915.4560

In [108]:
joined_df.groupby('year').sum()

price      num_bags        market
year                                     
2015  3026.92  7.481009e+08  7.730535e+08
2016  3104.51  1.398101e+09  1.437407e+09
2017  3705.97  1.541193e+09  1.822195e+09
2018   730.87  4.593696e+08  4.812983e+08

In [109]:
ans['Q15'] = 3

# Data Science Basics

the following questions reference material from the first lecture (Tuesday 5.3) and should be answered after the lecture.

## Basic definitions
#### Q16.	Which of the following is not primarily a data science project: 

1.	Collect and analyze data from a linear accelerator, looking for a new particle

2.	Build a robot which serves cocktail drinks

3.	Given two website designs, test which one attracts more traffic

4.	Do an online poll to predict the outcome of an election


In [110]:
ans['Q16'] = 2

#### We mentioned in class that data science has three interweaved components: Computing expertise, statistical expertise, domain expertise (Physics). Consider the following tasks involved in a hypothetical data science project to find a new particle: 

1.	Designing the database to hold results

2.	Deciding which signals should be collected, and what kind of signals we are looking for to identify a new particle

3.	Fitting regression models to the data and performing statistical tests in search of the signals

4.  Recruiting the right personnel to carry out the project 

#### Q17. Which one of the above most clearly belongs to the statistical expertise category?
#### Q18. Which one most clearly belongs to the computing expertise category?
#### Q19. Which one most clearly belongs to the domain expertise category?

In [ ]:
ans['Q17'] = #### your answer here ####
ans['Q18'] = #### your answer here ####
ans['Q19'] = #### your answer here ####

# finish!

to submit your HW please run this last code block and follow the instructions. <BR>
this code will create a CSV file in the current directory on the azure notebooks project <br>
please download it and send it to us at: dorongurel@mail.tau.ac.il with the mail title: `intro2ds-hw1`<br>
we will then send you a confirmation that the file was recieved.

In [ ]:
df_ans = pd.DataFrame.from_dict(ans, orient='index')
df_ans.to_csv('{}_{}.csv'.format(ans['HW'],str(ans['id_number'])))